name: caddy

services:

  caddy:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../workspace/my-admin/dist:/srv/my-admin:ro
      # - ./prod:/srv/prod:ro
      # - ./_generated/Caddyfile:/etc/caddy/Caddyfile

  # keycloak:
  #   image: keycloak/keycloak:14
  #   container_name: keycloak
  #   restart: unless-stopped
  #   environment:
  #     KC_HOSTNAME: prod.mediactil.com
  #     KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
  #     KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
  #     KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  #     KC_HEALTH_ENABLED: "true"
  #     KC_LOG_LEVEL: info
  #     KC_PROXY: edge
  #   # healthcheck:
  #   #   test: ["CMD", "curl", "-f", "http://keycloak:8080/health/ready"]
  #   #   interval: 15s
  #   #   timeout: 2s
  #   #   retries: 15
  #   command: ["start-dev", "--http-port", "8080"]

  # keycloak:
  #   image: keycloak/keycloak
  #   container_name: keycloak
  #   restart: unless-stopped
  #   environment:
  #     # Admin credentials
  #     KC_BOOTSTRAP_ADMIN_USERNAME: ${ADMIN_USERNAME}
  #     KC_BOOTSTRAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  #     # Proxy configuration
  #     KC_PROXY_HEADERS: xforwarded
  #     KC_HTTP_ENABLED: "true"
  #     KC_HTTP_PORT: 8080
  #     # Hostname configuration
  #     KC_FEATURES: "hostname:v2"
  #     KC_HOSTNAME: "https://prod.mediactil.com/keycloak"
  #     KC_HOSTNAME_STRICT: "false"
  #     # # Health checks
  #     # KC_HEALTH_ENABLED: "true"
  #     # Logging
  #     KC_LOG_LEVEL: info
  #   command: ["start-dev"]

networks:
  default:
    name: web
    external: true

volumes:
  caddy_data:
  caddy_config:
